name: Ubuntu CI

on:
  push:
    paths:
    - '*.pro'
    - 'src/**'
    - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
    - '*.pro'
    - 'src/**'
    - '.github/workflows/ubuntu.yml'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        qt_ver: [5.15.2]
        qt_arch: [gcc_64]
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_ver }}
        cached: 'false'
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 1

    - name: Build Ubuntu
      run: |
        qmake
        make -j8
